name: Terraform GitOps Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_REGION_NAME: ${{ vars.HW_REGION_NAME }}


    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Initialize Terraform
      - name: Terraform Yum
        run: |
          cd master-acc/
          terraform init \
            -backend-config="bucket=terraform-state-bucket" \
            -backend-config="key=master/terraform.tfstate" \
            -backend-config="region=$HW_REGION_NAME" \
            -backend-config="endpoint=https://obs.ap-southeast-2.myhuaweicloud.com" \
            -backend-config="access_key=$HW_ACCESS_KEY" \
            -backend-config="secret_key=$HW_SECRET_KEY" \
            -backend-config="skip_region_validation=true" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_requesting_account_id=true" \
            -backend-config="skip_s3_checksum=true"
          terraform apply -auto-approve \
            -var="access_key=$HW_ACCESS_KEY" \
            -var="secret_key=$HW_SECRET_KEY"



      
      

