name: HWC-GitOps

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform GitOps Workflow
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_REGION_NAME: ${{ vars.HW_REGION_NAME }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Terraform binary
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform
          key: terraform-${{ runner.os }}-v1
          restore-keys: |
            terraform-${{ runner.os }}-v1

      # Install Terraform if cache miss
      - name: Install Terraform
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update -y
          sudo apt-get install -y terraform

      # Initialize Terraform and apply
      - name: Terraform Init and Apply
        run: |
          cd network-acc/
          terraform init
          terraform apply -auto-approve



      
      

