name: Terraform Action

on:
  push:
    branches:
      - main
    paths:
      - 'master-acc/**'
      - 'network-acc/**'
      - '.github/workflows/**'
  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    env: # Define environment variables using GitHub Secrets
      HW_REGION_NAME: ${{ vars.REGION }}
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AHW_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false

      - name: Terraform Apply for Each Folder
        run: |
          for dir in master-acc network-acc; do
            echo "Processing folder: $dir"
            cd $dir
            terraform init
            terraform apply -auto-approve
            cd ..
          done
        env: # Define environment variables using GitHub Secrets
          HW_REGION_NAME: ${{ vars.REGION }}
          HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
          HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AHW_SECRET_KEY }}
      
      

